### ISSUE TITLE
Adaptar código de conducta al mundo offline

### ISSUE THREAD

**Issue by sergioalvz** [asturiashacking/core#1]
Hola,

ya que nosotros formamos parte de una Comunidad que tiene tanto participación *online* como *offline*, creo que tenemos que hacer algún que otro ajuste para dejar también constancia ahí de que no vamos a permitir ningún comportamiento o comentario que infrinja este código de conducta durante el desarrollo de cualquier evento.

@tasugo, ¿qué opinas?

**Comment by tasugo** [comment]
Me parece perfecto, le doy para adelante a la PR :)
